### ISSUE TITLE
DeleteMany/ Delete Query

### ISSUE THREAD

**Issue by mohit6522** [oracle/nosql-python-sdk#1]
Is there a way to delete multiple records(on line of Oracle SQL Delete and Truncate)? Also can we delete based on column name, field names similar to using delete with where clause(no just on primary key)?

**Comment by gmfeinberg** [comment]
Hi,
There is a request that allows you to delete multiple rows as long as they share the same shard key. It is the MultiDeleteRequest. There's an example in examples/multi_data_ops.py

As for the second part of your question, no, it's not possible to delete via SQL query without a primary key.
